
export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE'

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE'

// Send like to parner
export const SEND_LIKE_REQUEST = 'SEND_LIKE_REQUEST'
export const SEND_LIKE_SUCCESS = 'SEND_LIKE_SUCCESS'
export const SEND_LIKE_FAILURE = 'SEND_LIKE_FAILURE'

// Constants for get people liked me
export const GET_PEOPLE_LIKED_ME_REQUEST = 'GET_PEOPLE_LIKED_ME_REQUEST'
export const GET_PEOPLE_LIKED_ME_SUCCESS = 'GET_PEOPLE_LIKED_ME_SUCCESS'
export const GET_PEOPLE_LIKED_ME_FAILURE = 'GET_PEOPLE_LIKED_ME_FAILURE'

// update user profile
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE'

// delete user pictures
export const DELETE_USER_PICTURE_REQUEST = 'DELETE_USER_PICTURE_REQUEST'
export const DELETE_USER_PICTURE_SUCCESS = 'DELETE_USER_PICTURE_SUCCESS'
export const DELETE_USER_PICTURE_FAILURE = 'DELETE_USER_PICTURE_FAILURE'

// Constants for getting recommendation self introduction
export const GET_SELF_INTRODUCTION_REQUEST = 'GET_SELF_INTRODUCTION_REQUEST'
export const GET_SELF_INTRODUCTION_SUCCESS = 'GET_SELF_INTRODUCTION_SUCCESS'
export const GET_SELF_INTRODUCTION_FAILURE = 'GET_SELF_INTRODUCTION_FAILURE'

// Constants for validating image to upload
export const UPLOAD_IMAGE_VALIDATE_REQUEST = 'UPLOAD_IMAGE_VALIDATE_REQUEST'
export const UPLOAD_IMAGE_VALIDATE_SUCCESS = 'UPLOAD_IMAGE_VALIDATE_SUCCESS'
export const UPLOAD_IMAGE_VALIDATE_FAILURE = 'UPLOAD_IMAGE_VALIDATE_FAILURE'

// Constants for uploading image
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'

// Constants for getting face book albums
export const GET_FB_ALBUM_REQUEST = 'GET_FB_ALBUM_REQUEST'
export const GET_FB_ALBUM_SUCCESS = 'GET_FB_ALBUM_SUCCESS'
export const GET_FB_ALBUM_FAILURE = 'GET_FB_ALBUM_FAILURE'

// Constants for getting face book pictures
export const GET_FB_PICTURE_REQUEST = 'GET_FB_PICTURE_REQUEST'
export const GET_FB_PICTURE_SUCCESS = 'GET_FB_PICTURE_SUCCESS'
export const GET_FB_PICTURE_FAILURE = 'GET_FB_PICTURE_FAILURE'

// Constants for synchronize face book pictures
export const SYNCH_FB_PICTURE_REQUEST = 'SYNCH_FB_PICTURE_REQUEST'
export const SYNCH_FB_PICTURE_SUCCESS = 'SYNCH_FB_PICTURE_SUCCESS'
export const SYNCH_FB_PICTURE_FAILURE = 'SYNCH_FB_PICTURE_FAILURE'

// Constants for add user to favorite list
export const ADD_FAVORITE_REQUEST = 'ADD_FAVORITE_REQUEST'
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS'
export const ADD_FAVORITE_FAILURE = 'ADD_FAVORITE_FAILURE'

// Constants for delete user from favorite list
export const DELETE_FAVORITE_REQUEST = 'DELETE_FAVORITE_REQUEST'
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS'
export const DELETE_FAVORITE_FAILURE = 'DELETE_FAVORITE_FAILURE'

// Constants for get user from favorite list
export const GET_FAVORITE_REQUEST = 'GET_FAVORITE_REQUEST'
export const GET_FAVORITE_SUCCESS = 'GET_FAVORITE_SUCCESS'
export const GET_FAVORITE_FAILURE = 'GET_FAVORITE_FAILURE'

// Constants for VISITANTS
export const GET_VISITANT_REQUEST = 'GET_VISITANT_REQUEST'
export const GET_VISITANT_SUCCESS = 'GET_VISITANT_SUCCESS'
export const GET_VISITANT_FAILURE = 'GET_VISITANT_FAILURE'

// Constants for Delete my account
export const DELETE_MY_ACCOUNT_REQUEST = 'DELETE_MY_ACCOUNT_REQUEST'
export const DELETE_MY_ACCOUNT_SUCCESS = 'DELETE_MY_ACCOUNT_SUCCESS'
export const DELETE_MY_ACCOUNT_FAILURE = 'DELETE_MY_ACCOUNT_FAILURE'

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST'
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS'
export const BLOCK_USER_FAILURE = 'BLOCK_USER_FAILURE'

export const UNBLOCK_USER_REQUEST = 'UNBLOCK_USER_REQUEST'
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS'
export const UNBLOCK_USER_FAILURE = 'UNBLOCK_USER_FAILURE'
export const BLOCK_NOTIFICATION = 'BLOCK_NOTIFICATION'
export const UNBLOCK_NOTIFICATION = 'UNBLOCK_NOTIFICATION'

export const GET_BLOCKED_USERS_REQUEST = 'GET_BLOCKED_USERS_REQUEST'
export const GET_BLOCKED_USERS_SUCCESS = 'GET_BLOCKED_USERS_SUCCESS'
export const GET_BLOCKED_USERS_FAILURE = 'GET_BLOCKED_USERS_FAILURE'

export const GET_WHO_ADD_ME_TO_FAVOURITE_REQUEST = 'GET_WHO_ADD_ME_TO_FAVOURITE_REQUEST'
export const GET_WHO_ADD_ME_TO_FAVOURITE_SUCCESS = 'GET_WHO_ADD_ME_TO_FAVOURITE_SUCCESS'
export const GET_WHO_ADD_ME_TO_FAVOURITE_FAILURE = 'GET_WHO_ADD_ME_TO_FAVOURITE_FAILURE'

export const UPDATE_USER_PROFILE_STATE = 'UPDATE_USER_PROFILE_STATE'

// Constants for getting matched users
export const GET_MATCHED_USERS_REQUEST = 'GET_MATCHED_USERS_REQUEST'
export const GET_MATCHED_USERS_SUCCESS = 'GET_MATCHED_USERS_SUCCESS'
export const GET_MATCHED_USERS_FAILURE = 'GET_MATCHED_USERS_FAILURE'
export const UPDATE_MATCHED_NOTIFICATION = 'UPDATE_MATCHED_NOTIFICATION';
export const DECREASE_NOTIFICATION_NUMBER = 'DECREASE_NOTIFICATION_NUMBER';

export const INCREASE_VISITANT_NUMBER = 'INCREASE_VISITANT_NUMBER'
export const INCREASE_NOTIFICATION_NUMBER = 'INCREASE_NOTIFICATION_NUMBER'
export const PEOPLE_LIKE_ME_REAL_TIME = 'PEOPLE_LIKE_ME_REAL_TIME'
export const VISITANT_REAL_TIME = 'VISITANT_REAL_TIME'

export const CLEAR_NOTIFICATION_REQUEST = 'CLEAR_NOTIFICATION_REQUEST'
export const CLEAR_NOTIFICATION_SUCCESS = 'CLEAR_NOTIFICATION_SUCCESS'
export const CLEAR_NOTIFICATION_FAILURE = 'CLEAR_NOTIFICATION_FAILURE'

export const SHOW_CHAT_NOTIFICATION_REQUEST = 'SHOW_CHAT_NOTIFICATION_REQUEST'
export const SHOW_CHAT_NOTIFICATION_SUCCESS = 'SHOW_CHAT_NOTIFICATION_SUCCESS'
export const SHOW_CHAT_NOTIFICATION_FAILURE = 'SHOW_CHAT_NOTIFICATION_FAILURE'

export const HIDDEN_LIKE_REQUEST = 'HIDDEN_LIKE_REQUEST'
export const HIDDEN_LIKE_SUCCESS = 'HIDDEN_LIKE_SUCCESS'
export const HIDDEN_LIKE_FAILURE = 'HIDDEN_LIKE_FAILURE'

export const SET_AVATAR_REQUEST = 'SET_AVATAR_REQUEST'
export const SET_AVATAR_SUCCESS = 'SET_AVATAR_SUCCESS'
export const SET_AVATAR_FAILURE = 'SET_AVATAR_FAILURE'

export const UPDATE_WELCOMEPAGE_COMPLETION_REQUEST = 'UPDATE_WELCOMEPAGE_COMPLETION_REQUEST'
export const UPDATE_WELCOMEPAGE_COMPLETION_SUCCESS = 'UPDATE_WELCOMEPAGE_COMPLETION_SUCCESS'
export const UPDATE_WELCOMEPAGE_COMPLETION_FAILURE = 'UPDATE_WELCOMEPAGE_COMPLETION_FAILURE'

export const UPDATE_SHOWED_RECOMMENDATION_STATUS = 'UPDATE_SHOWED_RECOMMENDATION_STATUS'
export const UPDATE_ASKED_LOCATION_STATUS = 'UPDATE_ASKED_LOCATION_STATUS'
export const UPDATE_PAYMENT_PACKAGE_REQUEST = 'UPDATE_PAYMENT_PACKAGE_REQUEST'
export const UPDATE_PAYMENT_PACKAGE_SUCCESS = 'UPDATE_PAYMENT_PACKAGE_SUCCESS'
export const UPDATE_PAYMENT_PACKAGE_FAILURE = 'UPDATE_PAYMENT_PACKAGE_FAILURE'

export const UPDATE_FREE_CHAT_REQUEST = 'UPDATE_FREE_CHAT_REQUEST'
export const UPDATE_FREE_CHAT_SUCCESS = 'UPDATE_FREE_CHAT_SUCCESS'
export const UPDATE_FREE_CHAT_FAILURE = 'UPDATE_FREE_CHAT_FAILURE'

export const UPDATE_LOCATION_REQUEST = 'UPDATE_LOCATION_REQUEST'
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS'
export const UPDATE_LOCATION_FAILURE = 'UPDATE_LOCATION_FAILURE'

export const ACTIVE_BOOST_RANK_REQUEST = 'ACTIVE_BOOST_RANK_REQUEST'
export const ACTIVE_BOOST_RANK_SUCCESS = 'ACTIVE_BOOST_RANK_SUCCESS'
export const ACTIVE_BOOST_RANK_FAILURE = 'ACTIVE_BOOST_RANK_FAILURE'

export const UPLOADED_VERIFY_IMAGE = 'UPLOADED_VERIFY_IMAGE';
export const UPDATE_LIKE_STYLE = 'UPDATE_LIKE_STYLE'
export const UPDATE_LIKED_MY_PHOTO_MODAL = 'UPDATE_LIKED_MY_PHOTO_MODAL'
export const UPDATE_FIRST_LIKE_STATUS = 'UPDATE_FIRST_LIKE_STATUS';
export const UPDATE_VOTED_USERS = 'UPDATE_VOTED_USERS';

export const BLOCK_TYPE_BLOCKED = 1
export const BLOCK_TYPE_MUTED = 2

export const ACTIVE_USER = 1
export const BAD_USER = 2
export const DEACTIVE_USER = 3

export const COVER_PICTURE = 1
export const AVATAR_PICTURE = 2
export const OTHER_PICTURE = 3
export const VERIFY_PICTURE_TYPE = 4

export const UPLOAD_DEVIDE_MODE = 1
export const UPLOAD_FACEBOOK_MODE = 2

export const MAXIMUM_USER_HOBBIES = 3
export const MAXIMUM_PERSONAL_STYLE = 5
export const MAXIMUM_HOBBY_TEXT_SIZE = 20
export const MAXIMUM_TEXT_SIZE = 50
export const MAXIMUM_SELF_INTRO_TEXT_SIZE = 1024
export const MINIMUM_SELF_INTRO_TEXT_SIZE = 20
export const MAXIMUM_NAME_TEXT_SIZE = 10

export const NOTIFICATION_TYPE_LIKE = 1
export const NOTIFICATION_TYPE_CHAT = 2 // chat notification from ymeetme only
export const NOTIFICATION_TYPE_CHAT_APP = 4 // chat notification from chat app
export const NOTIFICATION_TYPE_VIEW_MY_PROFILE = 3
export const NOTIFICATION_TYPE_VIEW_WHO_ADD_FAVOURITE = 6
export const BLOCKED_USER_CODE = '13'

export const VERIFICATION_NOT_APPROVE_STATUS = 0
export const VERIFICATION_PENDING_APPROVE_STATUS = 1
export const VERIFICATION_APPROVE_STATUS = 2

export const VOTE_BUTTON_VOTE = 1
export const VOTE_BUTTON_VIEW = 2
export const VOTE = 1
export const UNVOTE = 2